### ISSUE TITLE
Prioritize GMCP affliction tracking.

### ISSUE THREAD

**Issue by sailgoat** [sailgoat/WunderSys#6]
The system previously relied on GMCP afflictions in case a line was not delivered as expected. I'd like to pivot here and reverse this strategy. Aside from specific situations that server-side curing does not currently handle all afflictions will be tracked when received from a GMCP update.

**Comment by tynil** [comment]
Quick background: it previously had only the affliction lines for tracking. When I added GMCP aff tracking, I didn't bother tearing out the existing lines, since when they were duplicated, it didn't really break anything.

From what I remember, the one feature I couldn't replicate fully with GMCP aff tracking was correctly labeling which aff line gave you which affliction. E.g. putting (+Paralysis) after a line that gives you paralysis. The GMCP data triggered on a prompt line. You could find and replace the line before it, assuming that was the line that gave you the affliction, but that only worked if that line immediately before was the aff line. If you received two afflictions on 2+ lines (dstab/dsl), you might miss displaying that extra (+aff) line.

Personally, I never used those (+Aff) echos anyway, but I didn't know if a lot of people liked them. I would definitely re-test all this yourself to double check, because things could have changed, or I could be mistaken.

Other than that potential loss of functionality, I agree, GMCP is much preferred.

**Comment by pluggema** [comment]
I think we could work around that issue if we append those +aff echos to the prompt on which the aff was registered? I'm just thinking out loud here, I currently have the echos (gain/lose affs) on, but it's to spammy for me right now. Bashing Qurnok alone makes my head hurt looking at what it generates on handling voyra alone.

**Comment by pluggema** [comment]
I've added GAGCURING to see if that made any difference and I think I like it. You can compare [without](https://ada-young.appspot.com/pastebin/b090d7ee) vs [with](https://ada-young.appspot.com/pastebin/1fc8cc79) from my pastebins. Note that both have affgainedechos and affcuredechos set to false.
